### ISSUE TITLE
Seems like Single objects dropped after long time in background

### ISSUE THREAD

**Issue by lidorDF** [InsertKoinIO/koin#595]
**Describe the bug**
It seems that Single objects drops after the application returns from a long idle time in background

**To Reproduce**
1. Open App
2. Go to background
3. Wait couple of hours, open other apps and keep the device idle
4. Open the app from recent app, the app opens but singleton repository are empty

**Expected behavior**
Single objects needs to be saved

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-android + koin-androidx-scope + koin-androidx-viewmodel version 2.0.0-GA4`

**Additional moduleDefinition**
single<UsersRepo> {
        UsersRepoImpl(
            get<StoreManager>(),
            get<UserService>(),
            get<BuddyProgramService>(),
            get<PusherManager>()
        )
    }

Is there a way to know if Koin was stopped / cleared to restart the app?

**Comment by erickok** [comment]
This is just how Android works. Your app process got killed in the background and so a new startup has 'empty' singletons. The fact that you open from recetns jsut means that Android will try to rebuild your activity stack and it seems you code doesn't understand how to handle that. Nothing Koin-specific about that.

**Comment by svenjacobs** [comment]
As @erickok said this is Android's default behaviour and has nothing to do with Koin. If you need to persist (view) data you have many options, for instance [ViewModel with saved state](https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate).

**Comment by lidorDF** [comment]
Thanks for your response and the amazing library, we really love it. The issue was fixed :)

**Comment by ahmed2146** [comment]
Hi, i'm still facing this issue, on android 12, with koin version io.insert-koin:koin-bom:3.5.1

**Comment by thejohnsondev** [comment]
> Hi, i'm still facing this issue, on android 12, with koin version io.insert-koin:koin-bom:3.5.1

as @svenjacobs said, it has nothing to do with Koin. Android system can kill any object if the app process is old or if there is not enough memory. You need to think about implementing restoring the singleton state. You may consider shared viewmodels (or activity viewmodels)
